config/routes.rb
# frozen_string_literal: true

Archangel::Engine.routes.draw do
  # GET    /account/login
  # POST   /account/login
  # DELETE /account/logout
  # POST   /account/password
  # GET    /account/password/new
  # GET    /account/password/edit
  # PATCH  /account/password
  # PUT    /account/password
  # GET    /account/cancel
  # POST   /account
  # GET    /account/register
  # GET    /account/edit
  # PATCH  /account
  # PUT    /account
  # DELETE /account
  # POST   /account/verification
  # GET    /account/verification/new
  # GET    /account/verification
  # POST   /account/unlock
  # GET    /account/unlock/new
  # GET    /account/unlock
  # GET    /account/invitation/accept
  # GET    /account/invitation/remove
  # POST   /account/invitation
  # GET    /account/invitation/new
  # PATCH  /account/invitation
  # PUT    /account/invitation
  devise_for :users,
             module: :devise,
             class_name: "Archangel::User",
             controllers: {
               invitations: "archangel/auth/invitations",
               registrations: "archangel/auth/registrations"
             },
             path: "",
             path_prefix: Archangel.config.auth_path,
             skip: %i[omniauth_callbacks],
             path_names: {
               sign_in: "login",
               sign_out: "logout",
               sign_up: "register",
               password: "password",
               confirmation: "verification",
               unlock: "unlock"
             }

  # GET /account => /account/login
  get Archangel.config.auth_path,
      to: redirect("#{Archangel.config.auth_path}/login")

  namespace :backend, path: Archangel.config.backend_path do
    # GET    /backend/profile/edit
    # GET    /backend/profile
    # PATCH  /backend/profile
    # PUT    /backend/profile
    # DELETE /backend/profile
    resource :profile, except: %i[create new]

    # GET   /backend/site/edit
    # GET   /backend/site
    # PATCH /backend/site
    # PUT   /backend/site
    resource :site, only: %i[edit show update]

    # GET    /backend/assets
    # POST   /backend/assets
    # GET    /backend/assets/new
    # GET    /backend/assets/[ID]/edit
    # GET    /backend/assets/[ID]
    # PATCH  /backend/assets/[ID]
    # PUT    /backend/assets/[ID]
    # DELETE /backend/assets/[ID]
    resources :assets do
      # POST  /backend/assets/wysiwyg
      # POST  /backend/assets/wysiwyg.json
      post "wysiwyg", on: :collection, defaults: { format: :json }
    end

    # GET    /backend/collections
    # POST   /backend/collections
    # GET    /backend/collections/new
    # GET    /backend/collections/[SLUG]/edit
    # GET    /backend/collections/[SLUG]
    # PATCH  /backend/collections/[SLUG]
    # PUT    /backend/collections/[SLUG]
    # DELETE /backend/collections/[SLUG]
    resources :collections do
      # GET    /backend/collections/[COLLECTION_SLUG]/entries
      # POST   /backend/collections/[COLLECTION_SLUG]/entries
      # GET    /backend/collections/[COLLECTION_SLUG]/entries/new
      # GET    /backend/collections/[COLLECTION_SLUG]/entries/[ID]/edit
      # GET    /backend/collections/[COLLECTION_SLUG]/entries/[ID]
      # PATCH  /backend/collections/[COLLECTION_SLUG]/entries/[ID]
      # PUT    /backend/collections/[COLLECTION_SLUG]/entries/[ID]
      # DELETE /backend/collections/[COLLECTION_SLUG]/entries/[ID]
      resources :entries do
        # POST  /backend/collections/[COLLECTION_SLUG]/entries/sort
        # POST  /backend/collections/[COLLECTION_SLUG]/entries/sort.json
        post "sort", on: :collection, defaults: { format: :json }
      end
    end

    # GET    /backend/designs
    # POST   /backend/designs
    # GET    /backend/designs/new
    # GET    /backend/designs/[ID]/edit
    # GET    /backend/designs/[ID]
    # PATCH  /backend/designs/[ID]
    # PUT    /backend/designs/[ID]
    # DELETE /backend/designs/[ID]
    resources :designs

    # GET    /backend/pages
    # POST   /backend/pages
    # GET    /backend/pages/new
    # GET    /backend/pages/[ID]/edit
    # GET    /backend/pages/[ID]
    # PATCH  /backend/pages/[ID]
    # PUT    /backend/pages/[ID]
    # DELETE /backend/pages/[ID]
    resources :pages

    # GET    /backend/users
    # POST   /backend/users
    # GET    /backend/users/new
    # GET    /backend/users/[USERNAME]/edit
    # GET    /backend/users/[USERNAME]
    # PATCH  /backend/users/[USERNAME]
    # PUT    /backend/users/[USERNAME]
    # DELETE /backend/users/[USERNAME]
    resources :users

    # GET    /backend/widgets
    # POST   /backend/widgets
    # GET    /backend/widgets/new
    # GET    /backend/widgets/[SLUG]/edit
    # GET    /backend/widgets/[SLUG]
    # PATCH  /backend/widgets/[SLUG]
    # PUT    /backend/widgets/[SLUG]
    # DELETE /backend/widgets/[SLUG]
    resources :widgets

    # GET /backend
    root to: "dashboards#show"
  end

  namespace :frontend, path: Archangel.config.frontend_path do
    # GET /[PERMALINK]
    get ":permalink", to: "pages#show", as: :page,
                      constraints: {
                        permalink: %r{[\w\-\/]+}
                      }

    # GET /
    root to: "homepages#show"
  end

  # GET /
  root to: "frontend/homepages#show"
end

app/controllers/archangel/backend/assets_controller.rb
# frozen_string_literal: true

module Archangel
  ##
  # @see Archangel::BackendController
  #
  module Backend
    ##
    # Backend assets controller
    #
    class AssetsController < BackendController
      include Archangel::Controllers::ResourcefulConcern

      ##
      # Create backend asset from WYSIWYG upload
      #
      # Formats
      #   JSON
      #
      # Request
      #   POST /backend/wysiwyg
      #   POST /backend/wysiwyg.json
      #
      # Parameters
      #   {
      #     "file": "local/path/to/new_file.gif"
      #   }
      #
      # Response
      #   {
      #     "success": true,
      #     "url": "file_name.gif"
      #   }
      #
      def wysiwyg
        asset = resource_wysiwyg_content

        resource = {
          success: asset.valid?,
          error: asset.errors.full_messages.first
        }

        resource = resource.merge(url: asset.file.url) if asset.save

        render json: resource.reject { |key, val| key == :error && val.blank? }
      end

      protected

      def permitted_resource_attributes
        %w[file file_name]
      end

      def resources_content
        @assets = current_site.assets
                              .order(file_name: :asc)
                              .page(page_num).per(per_page)

        authorize @assets
      end

      def resource_content
        resource_id = params.fetch(:id)

        @asset = current_site.assets.find_by!(id: resource_id)

        authorize @asset
      end

      def resource_new_content
        @asset = current_site.assets.new(resource_new_params)

        authorize @asset
      end

      def resource_wysiwyg_content
        wysiwyg_params = params.permit(permitted_attributes).reverse_merge(
          file_name: "#{SecureRandom.hex}.jpg"
        )

        @asset = current_site.assets.new(wysiwyg_params)

        authorize @asset
      end
    end
  end
end

app/controllers/archangel/backend/collections_controller.rb
# frozen_string_literal: true

module Archangel
  ##
  # @see Archangel::BackendController
  #
  module Backend
    ##
    # Backend collections controller
    #
    class CollectionsController < BackendController
      include Archangel::Controllers::ResourcefulConcern

      protected

      def permitted_resource_attributes
        [
          :name, :slug,
          fields_attributes: %i[id _destroy classification label required slug]
        ]
      end

      def resources_content
        @collections = current_site.collections
                                   .order(name: :asc)
                                   .page(page_num).per(per_page)

        authorize @collections
      end

      def resource_content
        resource_id = params.fetch(:id)

        @collection = current_site.collections.find_by!(slug: resource_id)

        authorize @collection
      end

      def resource_new_content
        @collection = current_site.collections.new(resource_new_params)

        @collection.fields.build if @collection.fields.blank?

        authorize @collection
      end
    end
  end
end

app/controllers/archangel/backend/dashboards_controller.rb
# frozen_string_literal: true

module Archangel
  ##
  # @see Archangel::BackendController
  #
  module Backend
    ##
    # Backend dashboards controller
    #
    class DashboardsController < BackendController
      include Archangel::Controllers::SkipAuthorizableConcern

      ##
      # Backend dashboard
      #
      # Formats
      #   HTML, JSON
      #
      # Request
      #   GET /backend
      #   GET /backend.json
      #
      def show; end
    end
  end
end

app/controllers/archangel/backend/designs_controller.rb
# frozen_string_literal: true

module Archangel
  ##
  # @see Archangel::BackendController
  #
  module Backend
    ##
    # Backend designs controller
    #
    class DesignsController < BackendController
      include Archangel::Controllers::ResourcefulConcern

      protected

      def permitted_resource_attributes
        %w[content name parent_id partial]
      end

      def resources_content
        @designs = current_site.designs
                               .order(name: :asc)
                               .page(page_num).per(per_page)

        authorize @designs
      end

      def resource_content
        resource_id = params.fetch(:id)

        @design = current_site.designs.find_by!(id: resource_id)

        authorize @design
      end

      def resource_new_content
        @design = current_site.designs.new(resource_new_params)

        authorize @design
      end
    end
  end
end

app/controllers/archangel/backend/entries_controller.rb
# frozen_string_literal: true

module Archangel
  ##
  # @see Archangel::BackendController
  #
  module Backend
    ##
    # Backend collection entries controller
    #
    class EntriesController < BackendController
      include Archangel::Controllers::ResourcefulConcern

      before_action :parent_resource_content

      ##
      # Update collection entry sort order
      #
      # Formats
      #   JSON
      #
      # Params
      #   [String] slug - the collection slug
      #
      # Request
      #   POST /backend/collections/:slug/entries/sort
      #   POST /backend/collections/:slug/entries/sort.json
      #
      # Parameters
      #   {
      #     "collection_entry": {
      #       "sort": {
      #         "id" => "1234",
      #         "position" => "1"
      #     }
      #   }
      #
      def sort
        entry = current_site.entries
                            .where(collection: @collection)
                            .find_by(id: sort_resource_params.dig(:sort, :id))

        authorize entry

        entry.insert_at(sort_resource_params.dig(:sort, :position).to_i)

        render json: { status: :accepted, success: true }, status: :accepted
      end

      protected

      def permitted_resource_attributes
        fields = @collection.fields.map(&:slug).map(&:to_sym)

        fields + %i[published_at]
      end

      def permitted_sort_attributes
        [
          sort: %i[id position]
        ]
      end

      def sort_resource_params
        params.clone.require(resource_scope).permit(permitted_sort_attributes)
      end

      def parent_resource_content
        collection_id = params.fetch(:collection_id)

        @collection = current_site.collections
                                  .find_by!(slug: collection_id)
      end

      def resources_content
        @entries = current_site.entries
                               .where(collection: @collection)
                               .page(page_num)
                               .per(per_page)

        authorize @entries
      end

      def resource_content
        resource_id = params.fetch(:id)

        @entry = current_site.entries
                             .where(collection: @collection)
                             .find_by!(id: resource_id)

        authorize @entry
      end

      def resource_new_content
        @entry = current_site.entries.where(collection: @collection).new(nil)

        if action_name.to_sym == :create
          @collection.fields.map(&:slug).each do |field|
            @entry.assign_attributes(field => resource_params.fetch(field, nil))
          end
        end

        authorize @entry
      end

      def resource_scope
        :collection_entry
      end

      def location_after_save
        backend_collection_entries_path(@collection)
      end
    end
  end
end

app/controllers/archangel/backend/pages_controller.rb
# frozen_string_literal: true

module Archangel
  ##
  # @see Archangel::BackendController
  #
  module Backend
    ##
    # Backend pages controller
    #
    class PagesController < BackendController
      include Archangel::Controllers::ResourcefulConcern

      helper Archangel::Backend::MetatagsHelper

      protected

      def permitted_resource_attributes
        [
          :content, :design_id, :homepage, :parent_id, :permalink,
          :published_at, :slug, :title,
          metatags_attributes: %i[id _destroy name content]
        ]
      end

      def resources_content
        @pages = current_site.pages
                             .order(title: :asc)
                             .page(page_num).per(per_page)

        authorize @pages
      end

      def resource_content
        resource_id = params.fetch(:id)

        @page = current_site.pages.find_by!(id: resource_id)

        authorize @page
      end

      def resource_new_content
        @page = current_site.pages.new(resource_new_params)

        @page.metatags.build if @page.metatags.blank?

        authorize @page
      end
    end
  end
end

app/controllers/archangel/backend/users_controller.rb
# frozen_string_literal: true

module Archangel
  ##
  # @see Archangel::BackendController
  #
  module Backend
    ##
    # Backend users controller
    #
    class UsersController < BackendController
      include Archangel::Controllers::ResourcefulConcern

      ##
      # Invite backend user
      #
      # Formats
      #   HTML, JSON
      #
      # Request
      #   POST /backend/users
      #   POST /backend/users.json
      #
      # Parameters
      #   {
      #     "user": {
      #       "name": "First Last",
      #       "username": "user_name",
      #       "role": "editor",
      #       "avatar": "/uploads/file.png",
      #       "email": "me@example.com"
      #     }
      #   }
      #
      def create
        user = resource_new_content

        respond_with user, location: -> { location_after_create }
      end

      ##
      # Update backend user
      #
      # Formats
      #   HTML, JSON
      #
      # Params
      #   [String] slug - the user username
      #
      # Request
      #   PATCH /backend/users/:slug
      #   PATCH /backend/users/:slug.json
      #   PUT   /backend/users/:slug
      #   PUT   /backend/users/:slug.json
      #
      # Parameters
      #   {
      #     "user": {
      #       "name": "First Last",
      #       "username": "user_name",
      #       "role": "editor",
      #       "avatar": "/uploads/file.png",
      #       "email": "me@example.com"
      #     }
      #   }
      #
      def update
        user = resource_content

        user.update_without_password(resource_params)

        respond_with user, location: -> { location_after_update }
      end

      protected

      def permitted_resource_attributes
        %w[email locale name remove_avatar role username]
      end

      def resources_content
        @users = current_site.users
                             .where.not(id: current_user.id)
                             .order(name: :asc)
                             .page(page_num).per(per_page)

        authorize @users
      end

      def resource_content
        resource_id = params.fetch(:id)

        @user = current_site.users
                            .where.not(id: current_user.id)
                            .find_by!(username: resource_id)

        authorize @user
      end

      def resource_new_content
        @user = current_site.users.new

        if action_name.to_sym == :create
          @user = current_site.users.invite!(resource_new_params, current_user)
        end

        authorize @user
      end
    end
  end
end

app/helpers/archangel/backend/metatags_helper.rb
# frozen_string_literal: true

module Archangel
  ##
  # Backend helpers
  #
  module Backend
    ##
    # Metatags helpers
    #
    module MetatagsHelper
      ##
      # Suggested site metatags
      #
      # @return [Array] suggested site metatags
      #
      def suggested_site_metatags
        %w[description keywords author copyright viewport
           google-site-verification] +
          suggested_bot_metatags +
          suggested_og_metatags +
          suggested_twitter_metatags
      end

      ##
      # Suggested metatags
      #
      # @return [Array] suggested metatags
      #
      def suggested_metatags
        %w[description keywords] +
          suggested_bot_metatags +
          suggested_og_metatags +
          suggested_twitter_metatags
      end

      protected

      def suggested_bot_metatags
        %w[googlebot robots]
      end

      def suggested_og_metatags
        %w[og:title og:image og:description]
      end

      def suggested_twitter_metatags
        %w[twitter:card twitter:description twitter:image twitter:title]
      end
    end
  end
end

app/views/archangel/backend/entries/_buttons.html.erb
<div class="btn-group pull-right" role="group" aria-label="Button group">
  <% if member_action? || new_action? %>
    <%= link_to(Archangel.t(:back), backend_collection_entries_path(@collection), class: "btn btn-link", role: "button") %>
  <% end %>

  <% if collection_action? || show_action? || edit_action? %>
    <%= link_to(Archangel.t(:new), new_backend_collection_entry_path(@collection), class: "btn btn-link", role: "button") %>
  <% end %>

  <% if show_action? %>
    <%= link_to(Archangel.t(:edit), edit_backend_collection_entry_path(@collection, @entry), class: "btn btn-link", role: "button") %>
  <% end %>

  <%= link_to(Archangel.t(:collection), backend_collection_path(@collection), class: "btn btn-link", role: "button") %>

  <% if show_action? || edit_action? %>
    <%= link_to(Archangel.t(:destroy), backend_collection_entry_path(@collection, @entry), class: "btn btn-link d-none d-md-inline-block",
                                                                                           role: "button",
                                                                                           method: :delete,
                                                                                           data: { confirm: Archangel.t(:are_you_sure) }) %>
  <% end %>
</div>

app/views/archangel/backend/entries/_entry.html.erb
<tr class="entry-<%= entry.published? ? "published" : "unpublished" %> entry-<%= entry.available? ? "available" : "unavailable" %>"
    data-sortable-item-id="<%= entry.id %>">
  <td class="text-center">
    <span class="sortable-handle" draggable="true"><%= Archangel.t(:sort) %></span>
  </td>
  <% fields.each.with_index do |field, index| %>
    <% cell_display = index > 1 ? "d-md-table-cell" : "d-table-cell" %>

    <td class="d-none <%= cell_display %>"><%= entry.value[field] %></td>
  <% end %>
  <td class="d-none d-lg-table-cell">
    <%= entry.published_at %>
  </td>
  <td class="actions text-right">
    <%= link_to(Archangel.t(:show), backend_collection_entry_path(entry.collection, entry), class: "btn btn-info btn-sm") %>
    <%= link_to(Archangel.t(:edit), edit_backend_collection_entry_path(entry.collection, entry), class: "btn btn-warning btn-sm") %>
    <%= link_to(Archangel.t(:destroy), backend_collection_entry_path(entry.collection, entry), class: "btn btn-danger btn-sm d-none d-md-inline-block",
                                                                                               method: :delete,
                                                                                               data: { confirm: Archangel.t(:are_you_sure) }) %>
  </td>
</tr>

app/views/archangel/backend/entries/_form.html.erb
<% form_url = entry.persisted? ? backend_collection_entry_path(collection, entry) : backend_collection_entries_path(collection) %>
<%= simple_form_for([:backend, collection, entry], as: :collection_entry,
                                                   url: form_url,
                                                   html: { autocomplete: "false" }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <% for field in collection.fields %>
      <%= f.input field.slug.to_sym, as: field.classification,
                                     label: field.label,
                                     required: field.required %>
    <% end %>

    <%= f.input :published_at, as: :date_time_picker %>
  </div>

  <div class="form-actions text-right">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/archangel/backend/entries/edit.html.erb
<div class="card card-default sticky-title rounded-0">
  <div class="card-body">
    <h2><%= Archangel.t(:edit_entry_resource, resource: @collection.name.singularize) %></h2>
  </div>
</div>

<div class="card entries-edit">
  <div class="card-header">
    <%= render "buttons" %>
  </div>

  <div class="card-body">
    <%= render "form", collection: @collection, entry: @entry %>
  </div>
</div>

app/views/archangel/backend/entries/index.html.erb
<div class="card card-default sticky-title rounded-0">
  <div class="card-body">
    <h2><%= Archangel.t(:index_resource, resource: @collection.name) %></h2>
  </div>
</div>

<div class="card entries-index">
  <div class="card-header">
    <%= render "buttons" %>
  </div>

  <div class="card-body">
    <% if @entries.present? %>

      <div class="table-responsive text-nowrap">
        <table class="table table-hover table-bordered table-striped">
          <thead>
            <tr>
              <th class="sort-handle text-center" scope="col">&nbsp;</th>
              <% @collection.fields.map(&:label)[0, 4].each.with_index do |field, index| %>
                <% cell_display = index > 1 ? "d-md-table-cell" : "d-table-cell" %>
                <th scope="col" class="d-none <%= cell_display %>"><%= field %></th>
              <% end %>
              <th scope="col" class="d-none d-lg-table-cell"><%= Archangel.t(:published_at) %></th>
              <th class="actions text-right" scope="col"><%= Archangel.t(:actions) %></th>
            </tr>
          </thead>

          <tbody id="sortable" data-sortable-url="<%= sort_backend_collection_entries_path(@collection) %>">
            <%= render partial: "entry", collection: @entries[0, 4],
                                         locals: { fields: @collection.fields.map(&:slug)[0, 4] } %>
          </tbody>
        </table>
      </div>

      <%= paginate @entries %>

    <% else %>

      <p class="no-resources">
        <%= Archangel.t(:no_resources, resources: @entries.model_name.human.pluralize.downcase) %>
      </p>

    <% end %>
  </div>
</div>

app/views/archangel/backend/entries/new.html.erb
<div class="card card-default sticky-title rounded-0">
  <div class="card-body">
    <h2><%= Archangel.t(:new_entry_resource, resource: @collection.name.singularize) %></h2>
  </div>
</div>

<div class="card entries-new">
  <div class="card-header">
    <%= render "buttons" %>
  </div>

  <div class="card-body">
    <%= render "form", collection: @collection, entry: @entry %>
  </div>
</div>

app/views/archangel/backend/entries/show.html.erb
<div class="card card-default sticky-title rounded-0">
  <div class="card-body">
    <h2><%= Archangel.t(:show_resource, resource: @collection.name.singularize) %></h2>
  </div>
</div>

<div class="card entries-show">
  <div class="card-header">
    <%= render "buttons" %>
  </div>

  <div class="card-body">
    <%- fields = @collection.fields.map { |item| item.slug } %>

    <% fields.each do |field| %>
      <p>
        <strong><%= field %>:</strong>
        <%= @entry.value[field] %>
      </p>
    <% end %>
  </div>
</div>